version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "sleep 10 && npm run migration:run && npm run seed && npm run dev"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: docexpress
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
