name: Keep Services Alive

on:
  schedule:
    - cron: "0 */6 * * *"   # roda a cada 6 horas
  workflow_dispatch:        # permite rodar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST
        run: |
          curl -s -o /dev/null \
            "https://erxkvayahhbndxxgdivz.supabase.co/rest/v1"

      - name: Ping Backend Render
        run: |
          curl -s -o /dev/null \
            "https://doc-express-backend.onrender.com/ping"
